### PR TITLE
Updating NPM packages to get solution to run locally

### PR DESCRIPTION
**Pull request by AndrewCook**

### CODE REVIEW

**Comment by Caseysch** [comment]
Also fixes security warning on minimist < 1.2.2 and kind-of  >= 6.0.0, < 6.0.3

**Comment by Caseysch** [comment]
Run `npm install --save-dev copy-webpack-plugin@6.0.3` to fix the remaining package vulnerability

**Comment by OmarTawfik** [comment]
I also suggest fixing the versions for these packages to make sure the environment is reproducible everywhere/between builds.

**Comment by kmelmon** [comment]
@AndrewCook  @Caseysch @OmarTawfik As per discussion in the last shiproom:  I'm happy to test out this change but I'm not sure what's required, and to be honest I'm not sure what the SmallBasic.Client project even builds.  Could someone tell me the steps to verify this change?  Thanks and sorry for the newbie questions!

@EdPrice-MSFT do you know anything about SmallBasic.Client?  It looks like it's a way to run SmallBasic in a standalone Electron app.  Is that correct and if so, are there instructions for installing/running it?

**Comment by OmarTawfik** [comment]
`SmallBasic.Client` builds the client-side assets for the website. It mainly runs webpack through two targets:

The first restores npm packages:

https://github.com/sb/smallbasic-editor/blob/2dd609431101d39aad023097ff678ab3b8350e3e/Source/SmallBasic.Client/SmallBasic.Client.csproj#L20-L24

The second compiles the webpack:

https://github.com/sb/smallbasic-editor/blob/2dd609431101d39aad023097ff678ab3b8350e3e/Source/SmallBasic.Client/SmallBasic.Client.csproj#L26-L43

Now these client assets can be used in one of two ways:

* [The electron entry point](https://github.com/sb/smallbasic-editor/blob/4cf523e49a064e6ef0fcb6e37f75fc296b216aa0/Source/SmallBasic.Client/Entries/Electron.ts) to run things in a standalone desktop application
* [The web entry point](https://github.com/sb/smallbasic-editor/blob/4cf523e49a064e6ef0fcb6e37f75fc296b216aa0/Source/SmallBasic.Client/Entries/Web.ts) to run things through a browser

They both then render the same html file and react app. You can test the server version in your browser normally through launching the server project from VS.

But for testing the desktop, you need to rebuild the solution with `/p:IsBuildingForDesktop=True`([used here](https://github.com/sb/smallbasic-editor/search?q=IsBuildingForDesktop)). This is used in a few places, but the most important one is shown below. It generates the script files used to actually launch the electron app (and lets you know where to call it):

https://github.com/sb/smallbasic-editor/blob/4383330bea5f570f5ddac6295660aa9e1c8cae7a/Source/SmallBasic.Editor/SmallBasic.Editor.csproj#L42-L46

**Comment by OmarTawfik** [comment]
Build fixed by #184, and packages were updated. Please rebase if you have any more concerns/suggestions.

**Pull request closed without merging**
