### PR TITLE
Shapes zooming and rotation relative to center

### LINKED ISSUE #87: Shapes rotation is not from the center
Shapes.Rotate rotates a shape not from it's center.
```
GW_DrawGrid()
x = 100
y = 80
width = 120
height = 240
GraphicsWindow.BrushColor = "#999999"
GraphicsWindow.FillRectangle(x, y, width, height)
GraphicsWindow.PenColor = "#0099FF"
GraphicsWindow.BrushColor = "#0099FF"
rect = Shapes.AddRectangle(width, height)
Shapes.Move(rect, x, y)
While "True"
  For angle = 5 To 360 Step 5
    Shapes.Rotate(rect, angle)
    If Math.Remainder(angle, 90) = 0 Then
      Program.Delay(1000)
    Else
      Program.Delay(200)
    EndIf
  EndFor
EndWhile

Sub GW_DrawGrid
  ' GraphicsWindow | draw grid
  _gw = GraphicsWindow.Width
  _gh = GraphicsWindow.Height
  _c100 = "#999999"
  _c10 = "#CCCCCC"
  For _x = 0 To _gw Step 10
    If Math.Remainder(_x / 10, 10) = 0 Then
      GraphicsWindow.PenColor = _c100 
    Else
      GraphicsWindow.PenColor = _c10
    EndIf
    GraphicsWindow.DrawLine(_x, 0, _x, _gh)
  EndFor
  For _y = 0 To _gh Step 10
    If Math.Remainder(_y / 10, 10) = 0 Then
      GraphicsWindow.PenColor = _c100
    Else
      GraphicsWindow.PenColor = _c10
    EndIf
    GraphicsWindow.DrawLine(0, _y, _gw, _y)
  EndFor
EndSub
```

### LINKED ISSUE #88: Shapes zooming is not from the center
Shapes.Zoom zooms a shape not from it's center but from it's top left corner.
```
GW_DrawGrid()
x = 100
y = 80
width = 120
height = 240
GraphicsWindow.PenWidth = 0
GraphicsWindow.BrushColor = "#0099FF"
rect = Shapes.AddRectangle(width, height)
Shapes.SetOpacity(rect, 50)
Shapes.Move(rect, x, y)
GraphicsWindow.BrushColor = "#999999"
GraphicsWindow.FillRectangle(x, y, width, height)
While "True"
  scale = 0.1
  While scale <= 20
    Shapes.Zoom(rect, scale, scale)
    Program.Delay(20)
    scale = scale * 2
  EndWhile
  scale = 20
  While 0.1 <= scale
    Shapes.Zoom(rect, scale, scale)
    Program.Delay(20)
    scale = scale / 2
  EndWhile
EndWhile

Sub GW_DrawGrid
  ' GraphicsWindow | draw grid
  _gw = GraphicsWindow.Width
  _gh = GraphicsWindow.Height
  _c100 = "#999999"
  _c10 = "#CCCCCC"
  For _x = 0 To _gw Step 10
    If Math.Remainder(_x / 10, 10) = 0 Then
      GraphicsWindow.PenColor = _c100 
    Else
      GraphicsWindow.PenColor = _c10
    EndIf
    GraphicsWindow.DrawLine(_x, 0, _x, _gh)
  EndFor
  For _y = 0 To _gh Step 10
    If Math.Remainder(_y / 10, 10) = 0 Then
      GraphicsWindow.PenColor = _c100
    Else
      GraphicsWindow.PenColor = _c10
    EndIf
    GraphicsWindow.DrawLine(0, _y, _gw, _y)
  EndFor
EndSub
```

### PR DESCRIPTION
**Pull request by alxnull**
Fixes #87 and fixes #88.

### CODE REVIEW

**Comment by nonkit** [comment]
@alxnull , thank you for trying to fix #87 and #88.  But rotation/zooming center should be the center of the shape but not the center of window.  So please check the code again.  Thanks.
The center of the shape may be calculated with it's position and size.

**Comment by alxnull** [comment]
@nonkit In which browser did you test this? For me, the fix works in Firefox (see images below) and Chromium-based browsers. However, this seems to be yet another feature not working in Edge. I'll see if I can do something about this.

grafik grafik

**Comment by nonkit** [comment]
@alxnull, I confirmed that #87 and #88 are fixed on Chrome but not on Edge.  Thanks.
I recommend you not to use CSS (style) for Edge.

**Comment by OmarTawfik** [comment]
Thanks @alxnull for fixing and @nonkit for confirming! :)

**Pull request merged**
