### PR TITLE
Case-insensitive IO blocking in TextWindow

### LINKED ISSUE #93: TextWindow.Read() doesn't block IO
```
x = TextWindow.read()
TextWindow.write(x)
```

### PR DESCRIPTION
**Pull request by alxnull**
Fixes #93.

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@alxnull thanks a lot for catching that! :)
Can we add tests for this?

**Comment by alxnull** [comment]
@OmarTawfik I added a similar fix for `Program.End()`/ `Program.Pause()` and also tried to add some tests.

**Comment by OmarTawfik** [comment]
Looks great @alxnull!
Can we also add tests for verifying `Pause` and `End`?
You can do something like
```
While "True"
   x = TextWindow.ReadNumber()
   TextWindow.WriteLine(x)
   If x = 2 Then
      Program.end()
   EndIf
EndWhile
```
And you can feed it `1`, `2`, and `3`, and make sure it only prints `1` and `2` before stopping.

**Comment by alxnull** [comment]
@OmarTawfik Done. Please have a look again :)

**Comment by OmarTawfik** [comment]
@alxnull awesome!

**Pull request merged**
