### PR TITLE
Fixed GetAllIndices()

### LINKED ISSUE #151: GetAllIndices returns values not indices
Array.GetAllindices returns values but indices.  Sample code:
```
param["x"] = 200
param["y"] = 100
index = Array.GetAllIndices(param)
TextWindow.WriteLine(index) ' 1=x;2=y;
```
Expected result (indices):
```
1=x;2=y;
```
Current result (values):
```
1=200;2=100;
```

### PR DESCRIPTION
**Pull request by alxnull**
Fixes #151. 

Great to see some activity in this repository again :)
I [occasionally contributed some fixes](https://github.com/sb/smallbasic-editor/pulls?q=is%3Apr+author%3Aalxnull+) to smallbasic-editor in the past and would love to get a bit more involved in this project. What are the current plans for SmallBasic? Is there anything other I can help with?

### CODE REVIEW

**Comment by OmarTawfik** [comment]
@alxnull thanks a lot!
I've been working on fixing a couple and merging fixes, but @EdPrice-MSFT  would probably be able to talk more about timeplans.
The issues list is active if you want to take on more things to implement/fix :)

**Comment by OmarTawfik** [comment]
I love that fix. Can we also add a test to confirm the fix and prevent future regressions?

**Comment by alxnull** [comment]
@OmarTawfik Thanks for the feedback. I added a test case for the fix.

**Comment by OmarTawfik** [comment]
You are awesome!

**Pull request merged**
